### ISSUE TITLE
Замечания по 1 лабе

### ISSUE THREAD

**Issue by nightnoryu** [x4n3xl0v3r/web_special#1]
1. Директорию data лучше удалить и больше не коммитить, либо еще лучше добавить в местный .gitignore, т.к. эти данные не относятся к исходникам программы
2. Все импорты

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/UserSurvey.php#L5-L8

Лучше объединить в файл в директории src, что-то типа common.inc.php, который будет подтягивать все остальные зависимости, а в главном скрипте импортить только его.

3. Это немного устаревший стиль проверки:

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/UserSurvey.php#L20

Лучше писать через строгое сравнение: `$currSurvey !== null`

4. Если лямбда-функции не обращаются к членам класса (посредством `$this`), всегда надо их помечать static.

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/src/Survey.php#L32-L37

Так объект класса не будет привязан к замыканию, что более эффективно работает во времени выполнения. Подробнее [тут](https://www.php.net/manual/en/functions.anonymous.php#functions.anonymous-functions.static).

5. Это устаревший способ создания массива

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/src/Survey.php#L26

Лучше использовать квадратные скобки `[]`.

6. После выбрасывания исключения выполнение прерывается, поэтому `return false` здесь избыточно.

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/src/Survey.php#L139-L140

7. Не обязательно определять разделитель пути вручную, т.к. в PHP есть константа `DIRECTORY_SEPARATOR`

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/src/SurveyFileStorage.php#L27-L34

8. Закомментированный код лучше выпиливать сразу, т.к. это по сути этот код бесполезен, но тем не менее он не выпилен, непонятно почему. Если что-то надо будет вернуть, всегда есть история в git

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/src/SurveyFileStorage.php#L87

9. Не указан возвращаемый тип

https://github.com/x4n3xl0v3r/web_special/blob/01aea9ce268ee4334a4e855cf33ff2b8dc6b2266/Task-UserSurvey/src/SurveyFileStorage.php#L218

**Comment by x4n3xl0v3r** [comment]
Исправил все, кроме 9.

метод
`private function openFile(string $fileKey, string $openMode='rt') `
возвращает файловый ресурс (return fopen(...)). Как для такой функции строго указать type hint?

**Comment by nightnoryu** [comment]
@x4n3xl0v3r если *очень* сильно хочется возвращать ресурс, можно указать через PHPDoc:

```php
/**
 * @return resouce
 */
private function openFile(string $fileKey, string $openMode='rt')
```

обычно так делают, когда нативный type hint не справляется.
